#!/usr/bin/env python3
"""
sync_service_catalog.py — Auto-genera artefactos desde configs/services.yml

Lee el registro canónico de servicios y regenera:
  1. scripts/verify-services.sh  — Health check bash script
  2. docs/SERVICE_CATALOG.md     — Tabla Markdown de todos los servicios

Con --propagate, lee configs/consumers.yml y propaga credenciales
del .env maestro de G_SV_Agent a los .env de proyectos satélite.

Uso:
  python scripts/sync_service_catalog.py                    (sync catalog)
  python scripts/sync_service_catalog.py --propagate        (sync + propagate credentials)
  python scripts/sync_service_catalog.py --propagate-only   (only propagate, skip catalog)
  python scripts/sync_service_catalog.py --dry-run          (preview, no writes)

Registrado en: docs/library/scripts.md
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVICES_YAML = ROOT / "configs" / "services.yml"
CONSUMERS_YAML = ROOT / "configs" / "consumers.yml"
MASTER_ENV = ROOT / ".env"
VERIFY_SCRIPT = ROOT / "scripts" / "verify-services.sh"
CATALOG_MD = ROOT / "docs" / "SERVICE_CATALOG.md"


# ---------------------------------------------------------------
# YAML parser (no external deps)
# ---------------------------------------------------------------

def parse_yaml_value(val: str):
    if not val or val == "null":
        return None
    if val in ("true", "True"):
        return True
    if val in ("false", "False"):
        return False
    if (val.startswith('"') and val.endswith('"')) or \
       (val.startswith("'") and val.endswith("'")):
        return val[1:-1]
    try:
        return int(val)
    except ValueError:
        pass
    return val


def load_services_yaml(path: Path) -> list[dict]:
    if not path.exists():
        print(f"ERROR: {path} not found", file=sys.stderr)
        sys.exit(1)

    services: list[dict] = []
    current: dict | None = None
    text = path.read_text(encoding="utf-8")

    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        # Top-level list items start at column 0 with "- "
        indent = len(line) - len(line.lstrip())
        if stripped.startswith("- ") and indent == 0:
            if current is not None:
                services.append(current)
            current = {}
            kv = stripped[2:].strip()
            if ":" in kv:
                key, val = kv.split(":", 1)
                current[key.strip()] = parse_yaml_value(val.strip())
        elif ":" in stripped and current is not None and indent > 0:
            # Skip nested list items (e.g. extra_containers sub-items)
            if stripped.startswith("- "):
                continue
            key, val = stripped.split(":", 1)
            current[key.strip()] = parse_yaml_value(val.strip())

    if current is not None:
        services.append(current)

    return services


# ---------------------------------------------------------------
# Generator: verify-services.sh
# ---------------------------------------------------------------

VERIFY_HEADER = '''#!/usr/bin/env bash
# ============================================================
# verify-services.sh
# Health check for all GEN_OS remote services
#
# AUTO-GENERATED by scripts/sync_service_catalog.py
# from configs/services.yml — DO NOT EDIT MANUALLY
#
# Usage: bash scripts/verify-services.sh
# ============================================================

set -uo pipefail

echo "============================================"
echo " GEN_OS - Service Health Check"
echo " Date: $(date '+%Y-%m-%d %H:%M:%S')"
echo "============================================"
echo ""

UP=0
DOWN=0
TOTAL=0

check_service() {
  local name="$1"
  local url="$2"
  TOTAL=$((TOTAL + 1))

  STATUS=$(curl -sf -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "$url" 2>/dev/null || echo "000")

  if [[ "$STATUS" =~ ^(200|301|302|303|307|308)$ ]]; then
    echo "  [UP]   $name ($url) - HTTP $STATUS"
    UP=$((UP + 1))
  else
    echo "  [DOWN] $name ($url) - HTTP $STATUS"
    DOWN=$((DOWN + 1))
  fi
}
'''

VERIFY_FOOTER = '''
echo ""
echo "============================================"
echo " Results: $UP UP / $DOWN DOWN / $TOTAL total"
echo " Readiness: $(( (UP * 100) / TOTAL ))%"
echo "============================================"
'''


def generate_verify_script(services: list[dict]) -> str:
    lines = [VERIFY_HEADER]

    # Group by category
    by_category: dict[str, list[dict]] = defaultdict(list)
    for svc in services:
        if svc.get("deployed") and svc.get("url_external"):
            by_category[svc.get("category", "Other")].append(svc)

    for category, svcs in by_category.items():
        lines.append(f'echo "--- {category} ---"')
        for svc in svcs:
            name = svc["name"]
            url = svc["url_external"]
            # Pad name for alignment
            lines.append(f'check_service "{name}"  "{url}"')
        lines.append('echo ""')

    lines.append(VERIFY_FOOTER)
    return "\n".join(lines)


# ---------------------------------------------------------------
# Generator: docs/SERVICE_CATALOG.md
# ---------------------------------------------------------------

def generate_catalog_md(services: list[dict]) -> str:
    today = date.today().isoformat()

    lines = [
        "---",
        "depends_on:",
        "  - configs/services.yml",
        "impacts:",
        "  - src/health.py",
        "  - scripts/verify-services.sh",
        "---",
        "",
        "# Service Catalog — GEN_OS Infrastructure",
        "",
        f"> Auto-generated by `scripts/sync_service_catalog.py` on {today}",
        f"> Source of truth: `configs/services.yml`",
        "> **Do not edit manually** — run `python scripts/sync_service_catalog.py`",
        "",
        f"**Total services: {len(services)}** "
        f"(deployed: {sum(1 for s in services if s.get('deployed'))})",
        "",
    ]

    # Group by category
    by_category: dict[str, list[dict]] = defaultdict(list)
    for svc in services:
        by_category[svc.get("category", "Other")].append(svc)

    # Summary table
    lines.append("## Summary by Category")
    lines.append("")
    lines.append("| Category | Count | Services |")
    lines.append("|----------|-------|----------|")
    for category, svcs in by_category.items():
        names = ", ".join(s["name"] for s in svcs)
        lines.append(f"| {category} | {len(svcs)} | {names} |")
    lines.append("")

    # Detailed table
    lines.append("## Full Service Registry")
    lines.append("")
    lines.append("| # | Name | Category | External URL | Port | VM | Version | Status | Description |")
    lines.append("|---|------|----------|-------------|------|-----|---------|--------|-------------|")

    for i, svc in enumerate(services, 1):
        name = svc.get("name", "?")
        cat = svc.get("category", "?")
        url = svc.get("url_external") or "—"
        port = svc.get("port_internal", "—")
        vm = svc.get("vm", "—")
        ver = svc.get("version", "—")
        deployed = "Deployed" if svc.get("deployed") else "Pending"
        desc = svc.get("description", "—")
        lines.append(f"| {i} | **{name}** | {cat} | {url} | {port} | {vm} | {ver} | {deployed} | {desc} |")

    lines.append("")

    # NocoBase instances detail section
    nocobase_svcs = [s for s in services if "nocobase" in s.get("name", "").lower() or "mira" in s.get("name", "").lower()]
    if nocobase_svcs:
        lines.append("## NocoBase Instances Detail")
        lines.append("")
        lines.append("| Instance | URL | Port | Version | DB | Deployed |")
        lines.append("|----------|-----|------|---------|-----|----------|")
        for svc in nocobase_svcs:
            name = svc.get("name", "?")
            url = svc.get("url_external") or "—"
            port = svc.get("port_internal", "—")
            ver = svc.get("version", "—")
            db = svc.get("db_name", "—")
            deployed = "Yes" if svc.get("deployed") else "No"
            lines.append(f"| {name} | {url} | {port} | {ver} | {db} | {deployed} |")
        lines.append("")

    # Port mapping section
    lines.append("## Internal Port Map (VM101 + VM100)")
    lines.append("")
    lines.append("| Port | Service | VM |")
    lines.append("|------|---------|-----|")
    port_entries = sorted(
        [(svc.get("port_internal", 0), svc["name"], svc.get("vm", "?"))
         for svc in services if svc.get("port_internal")],
        key=lambda x: (str(x[2]), x[0])
    )
    for port, name, vm in port_entries:
        lines.append(f"| {port} | {name} | {vm} |")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------
# Credential Propagation: consumers.yml → satellite .env files
# ---------------------------------------------------------------

def load_env_file(path: Path) -> dict[str, str]:
    """Read a .env file into a dict. Ignores comments and blank lines."""
    env = {}
    if not path.exists():
        return env
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        key, val = stripped.split("=", 1)
        val = val.strip()
        # Remove surrounding quotes
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
            val = val[1:-1]
        env[key.strip()] = val
    return env


def update_env_file(path: Path, updates: dict[str, str]) -> list[str]:
    """Update specific keys in a .env file, preserving comments and order.

    Returns list of changes made (for reporting).
    """
    if not path.exists():
        return [f"  SKIP {path} (file not found)"]

    lines = path.read_text(encoding="utf-8").splitlines()
    changes: list[str] = []
    keys_updated: set[str] = set()
    new_lines: list[str] = []

    for line in lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in updates:
                old_val = stripped.split("=", 1)[1].strip()
                # Remove quotes for comparison
                old_clean = old_val
                if len(old_clean) >= 2 and old_clean[0] == old_clean[-1] and old_clean[0] in ('"', "'"):
                    old_clean = old_clean[1:-1]

                new_val = updates[key]
                if old_clean != new_val:
                    new_lines.append(f"{key}={new_val}")
                    changes.append(f"  UPDATE {key}: {old_clean[:20]}*** -> {new_val[:20]}***")
                else:
                    new_lines.append(line)  # unchanged
                keys_updated.add(key)
                continue
        new_lines.append(line)

    # Append any keys that weren't found in the file
    missing = set(updates.keys()) - keys_updated
    if missing:
        new_lines.append("")
        new_lines.append("# --- Propagated from G_SV_Agent (auto-sync) ---")
        for key in sorted(missing):
            new_lines.append(f"{key}={updates[key]}")
            changes.append(f"  ADD    {key}={updates[key][:30]}***")

    if changes:
        path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")

    return changes


def load_consumers_yaml(path: Path) -> dict:
    """Parse consumers.yml into a structured dict.

    Returns: {
        'ecosystem_root': str,
        'projects': {
            'name': {
                'env_path': str,
                'description': str,
                'variables': [{'source': str, 'target': str, 'format': str|None, 'transform': str|None}]
            }
        }
    }
    """
    if not path.exists():
        print(f"ERROR: {path} not found", file=sys.stderr)
        sys.exit(1)

    text = path.read_text(encoding="utf-8")
    result: dict = {"ecosystem_root": "", "projects": {}}

    current_project: str | None = None
    current_section: str | None = None  # 'projects' or 'shared_credentials'
    in_variables = False  # True when we're inside a variables: list
    current_var: dict | None = None
    variables: list[dict] = []

    def _save_project():
        nonlocal current_var, variables
        if current_project:
            if current_var:
                variables.append(current_var)
                current_var = None
            result["projects"][current_project]["variables"] = variables
            variables = []

    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        indent = len(line) - len(line.lstrip())

        # Top-level keys (indent 0)
        if indent == 0 and ":" in stripped and not stripped.startswith("-"):
            _save_project()
            key, val = stripped.split(":", 1)
            key, val = key.strip(), val.strip()
            if key == "ecosystem_root":
                result["ecosystem_root"] = parse_yaml_value(val)
            elif key == "projects":
                current_section = "projects"
            elif key == "shared_credentials":
                current_section = "shared_credentials"
            current_project = None
            in_variables = False
            continue

        if current_section != "projects":
            continue

        # Project names (indent 2, not a list item)
        if indent == 2 and ":" in stripped and not stripped.startswith("-"):
            _save_project()
            name = stripped.split(":")[0].strip()
            current_project = name
            result["projects"][name] = {"env_path": "", "description": "", "variables": []}
            in_variables = False
            current_var = None
            continue

        if not current_project:
            continue

        # Project scalar properties (indent 4, not a list item)
        if indent == 4 and ":" in stripped and not stripped.startswith("-"):
            k, v = stripped.split(":", 1)
            k, v = k.strip(), v.strip()
            if k == "env_path":
                result["projects"][current_project]["env_path"] = parse_yaml_value(v)
            elif k == "description":
                result["projects"][current_project]["description"] = parse_yaml_value(v)
            elif k == "variables":
                in_variables = True
            continue

        # Variable list items (indent 6+, inside variables block)
        if in_variables and indent >= 6:
            if stripped.startswith("- "):
                # New variable entry
                if current_var:
                    variables.append(current_var)
                current_var = {}
                kv = stripped[2:].strip()
                if ":" in kv:
                    k, v = kv.split(":", 1)
                    current_var[k.strip()] = parse_yaml_value(v.strip())
            elif current_var is not None and ":" in stripped:
                # Continuation of current variable (target, format, transform)
                k, v = stripped.split(":", 1)
                current_var[k.strip()] = parse_yaml_value(v.strip())
            continue

    # Save final project
    _save_project()

    return result


def build_external_url_map(services: list[dict]) -> dict[str, str]:
    """Build a map from lowercase service name keywords to external URLs.

    Used by transform: external_url to resolve service external URLs.
    """
    url_map: dict[str, str] = {}
    for svc in services:
        name = svc.get("name", "")
        url = svc.get("url_external")
        if not url:
            continue
        # Index by each word in the service name (lowercase)
        for word in name.lower().replace("-", " ").replace("(", "").replace(")", "").split():
            # Avoid overly generic words
            if word in ("dev",):
                continue
            url_map[word] = url
        # Also index by full name
        url_map[name.lower()] = url
    return url_map


def resolve_transform(value: str, source_key: str, transform: str,
                      ext_url_map: dict[str, str]) -> str:
    """Apply a transform to a value.

    Transforms:
      - external_url: Replace with the service's external URL (from services.yml)
      - internal_url: Keep the master .env value as-is (already internal)
    """
    if transform == "internal_url":
        return value  # master .env values are internal by default

    if transform == "external_url":
        # Try to match source key to a service name
        source_lower = source_key.lower()
        for keyword, ext_url in ext_url_map.items():
            if keyword in source_lower:
                return ext_url
        # Fallback: return original value
        print(f"      WARN: No external URL found for {source_key}, using master value")
        return value

    return value


def propagate_credentials(dry_run: bool = False) -> int:
    """Propagate credentials from master .env to satellite projects.

    Returns number of projects updated.
    """
    consumers = load_consumers_yaml(CONSUMERS_YAML)
    master_env = load_env_file(MASTER_ENV)
    ecosystem_root = Path(consumers["ecosystem_root"])

    # Load services for external URL transforms
    services = load_services_yaml(SERVICES_YAML) if SERVICES_YAML.exists() else []
    ext_url_map = build_external_url_map(services)

    if not master_env:
        print("ERROR: Master .env is empty or not found", file=sys.stderr)
        return 0

    print(f"\nPropagating credentials from {MASTER_ENV}")
    print(f"  Master .env has {len(master_env)} variables")
    print(f"  Ecosystem root: {ecosystem_root}")
    print(f"  Projects: {len(consumers['projects'])}")
    print()

    updated_count = 0

    for proj_name, proj_config in consumers["projects"].items():
        env_path = ecosystem_root / proj_config["env_path"]
        variables = proj_config.get("variables", [])

        if not variables:
            continue

        print(f"  {proj_name} ({env_path})")

        if not env_path.exists():
            print(f"    SKIP -- .env file not found")
            continue

        # Build the updates dict
        updates: dict[str, str] = {}
        for var in variables:
            source_key = var.get("source", "")
            target_key = var.get("target", source_key)
            fmt = var.get("format")
            transform = var.get("transform")

            if source_key not in master_env:
                print(f"    WARN: {source_key} not found in master .env")
                continue

            value = master_env[source_key]

            # Apply transform (external_url / internal_url)
            if transform:
                value = resolve_transform(value, source_key, str(transform),
                                          ext_url_map)

            # Apply format template (e.g. "root@pam!AG={value}")
            if fmt:
                value = str(fmt).replace("{value}", value)

            updates[target_key] = value

        if not updates:
            print(f"    No updates needed")
            continue

        if dry_run:
            for target_key, value in updates.items():
                print(f"    WOULD SET {target_key}={value[:30]}***")
            updated_count += 1
        else:
            changes = update_env_file(env_path, updates)
            if changes:
                for change in changes:
                    print(f"    {change}")
                updated_count += 1
            else:
                print(f"    All values already in sync")

    return updated_count


# ---------------------------------------------------------------
# Main
# ---------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Sync service catalog from configs/services.yml")
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing files")
    parser.add_argument("--propagate", action="store_true", help="Also propagate credentials to satellite .env files")
    parser.add_argument("--propagate-only", action="store_true", help="Only propagate credentials (skip catalog sync)")
    args = parser.parse_args()

    # Catalog sync (unless --propagate-only)
    if not args.propagate_only:
        services = load_services_yaml(SERVICES_YAML)
        print(f"Loaded {len(services)} services from {SERVICES_YAML}")

        # Generate verify-services.sh
        verify_content = generate_verify_script(services)
        if args.dry_run:
            print(f"\n--- verify-services.sh ({len(verify_content)} bytes) ---")
            print(verify_content[:500] + "...\n")
        else:
            VERIFY_SCRIPT.write_text(verify_content, encoding="utf-8", newline="\n")
            print(f"  Written: {VERIFY_SCRIPT}")

        # Generate SERVICE_CATALOG.md
        catalog_content = generate_catalog_md(services)
        if args.dry_run:
            print(f"\n--- SERVICE_CATALOG.md ({len(catalog_content)} bytes) ---")
            print(catalog_content[:500] + "...\n")
        else:
            CATALOG_MD.write_text(catalog_content, encoding="utf-8", newline="\n")
            print(f"  Written: {CATALOG_MD}")

        if not args.dry_run:
            print(f"\nCatalog sync complete. {len(services)} services registered.")

    # Credential propagation
    if args.propagate or args.propagate_only:
        updated = propagate_credentials(dry_run=args.dry_run)
        print(f"\nPropagation complete. {updated} project(s) updated.")
        if not args.dry_run:
            print("Remember to commit satellite .env changes.")
    elif not args.propagate_only:
        print("Remember to commit the generated files.")
        print("Tip: Use --propagate to also sync credentials to satellite projects.")


if __name__ == "__main__":
    main()
